### ISSUE TITLE
Interaction between Julia and Stata

### ISSUE THREAD

**Issue by yanyu2015** [droodman/julia.ado#4]
For Python, Stata provides several ways of support, one of which is the Stata Function Interface ([sfi](https://www.stata.com/python/api17/index.html)). 

Would your command eventually achieve similar functionality?
Even if not all, does it support at least the following two functionalities in the future?

- Passing the return results of Stata commands into Julia as variables of corresponding types, not limited to just datasets.
- Passing results from Julia to corresponding variables in Stata, not limited to just scalars.

**Comment by droodman** [comment]
The package already includes a [basic Stata Plugin Interface](https://github.com/droodman/julia.ado/blob/master/stataplugininterface.jl). This is documented in the help file under "Stata interface functions" and fundamentally should allow the operations you describe.

The interface is not a full-featured as the Python interface. But it allows you to read and write the main Stata data set and Stata scalars, matrices, and macros. One limitation: it only works for global macros, not local.

Currently, yes, all data transferred from Stata to Julia comes through as double, because that is how [Stata's Plugin Interface for C](https://www.stata.com/plugins) works. Of course the data can be converted to other types once transferred.

I hope to add more functions to the interface that layer on top of the ones already provided. These would emulate the Python interface and add convenience. They could, for example, automate the conversion on the Julia side back to the original data type in Stata. Also, possibly by looking at the Python code for Stata's interface, I can learn about undocumented ways to access Stata objects, such as frames, through the C interface.

Or someone else can do it. PR's welcome!

**Comment by yanyu2015** [comment]
Thank you so much for your exceptional work! I eagerly await your upcoming release, and I was wondering if you could also consider providing additional documentation and more examples.

**Comment by droodman** [comment]
Each function [includes a docstring](https://github.com/droodman/julia.ado/blob/master/stataplugininterface.jl). And the functions definitions very closely follow those in the Stata Plugin Interface, which are documented [here](https://www.stata.com/plugins/#sect8a).

**Comment by yanyu2015** [comment]
thx. I notice the [rcall](https://github.com/haghish/rcall) package, which offers a convenient way to integrate Stata and R. It allows embedding any R code within Stata. Perhaps it can provide you with some inspiration as well.

**Comment by droodman** [comment]
Yes, I have used that.

**Comment by droodman** [comment]
I have added more interface functionality. And write-up with examples is [here](https://github.com/droodman/julia.ado/blob/master/doc/julia.pdf).
