### ISSUE TITLE
Problems with GetVarsFromDF

### ISSUE THREAD

**Issue by jmboehm** [droodman/julia.ado#6]
Thanks for the work on the package. I gave julia.ado a spin and ran into the following problem.

On MacOS 12.6.8 Monterey, with Stata MP/17.0, Julia 1.10.1, and julia.ado 0.9.0:

```stata
clear

// Run a "Hello World" to see that julia.ado works 
jl: "Hello world!"
// yep, works

// install the required packages
jl: import Pkg; Pkg.add(["RDatasets", "Revise", "DataFrames", "DataFramesMeta"])
jl: import Pkg; Pkg.add(url="https://github.com/jmboehm/Douglass.jl")
// load packages
jl: using Douglass, RDatasets, Test, DataFrames, DataFramesMeta

// load dataset in julia, and bring to Stata
jl: df = dataset("datasets", "iris")	
set obs 150
jl GetVarsFromDF SepalLength SepalWidth PetalLength PetalWidth , source(df) replace
```
leads to 
```
MethodError: Cannot `convert` an object of type Float64 to an object of type String

Closest candidates are:
  convert(::Type{Str
> ing}, !Matched::StringManipulation.Decoration)
   @ StringManipulation ~/.julia/packages/StringManipulation/5Zfrz/src/decoratio
> ns.jl:315
  convert(::Type{String}, !Matched::Base.JuliaSyntax.Kind)
   @ Base /Users/julia/.julia/scratchspaces/a66863c6-20e8-
> 4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-5.0/build/default-macmini-x64-5-0/julialang/julia-release-1-dot-10/base/
> JuliaSyntax/src/kinds.jl:975
  convert(::Type{String}, !Matched::String)
   @ Base essentials.jl:321
  ...
r(999);
```

On the other hand, this works fine:
```stata
jl GetVarsFromDFNoMissing SepalLength SepalWidth PetalLength PetalWidth , source(df) replace
```
The help file seems to imply that the difference between "NoMissing" and the base version is only that the latter is faster on a dataframe without missing values. `df` here contains a column `:Species` that is a `CategoricalArray`, perhaps that's part of the problem. I wasn't able to bring that over to Stata, even with `GetVarsFromDFNoMissing`.

As an aside, it took me a while to figure out that `set obs 150` was necessary, and it fails for me without that. It may be useful to have a separate subcommand of `jl` that just pulls all the column from a Julia DataFrame over and replaces the current Stata frame (perhaps `use`?), without having to worry about the number of rows etc.

**Comment by droodman** [comment]
Thanks for this feedback, @jmboehm. You inspired me to think of this package more broadly. I made it to prove a concept, and to serve as hidden infrastructure for other programs, like `reghdfejl` and `boottest`. I see this comment as asking me to make it work better for "retail" customers.

 On your suggestion, the last version adds `jl use` and `jl save` commands. They are documented in the help file. By default, the commands for transferring data between Stata and Julia DataFrames now pick appropriate types, rather than always using double-precision. The old behavior is still available in `PutVarsToDF` through a `doubleonly` option (it's faster). Strings are now handled too.

One complicated issue is how and whether to map between Julia categorical variables and Stata variables with data labels. Right now, it maps from the first to the second but not the other way. Stata variables with data labels are copied straight, without their labels. The underlying issue is that these two constructs are not quite equivalent. Stata code refers to labeled values by their real values, not their labels. If 1="yes", Stata code refers to the 1. But Julia code would refer directly to the "yes", for example to filter rows.

At this moment, I haven't recompiled for macOS, just Linux and Windows. I should fix that later today.

Also the "NoMissing" subcommands are gone. `nomissing` is now an option rather than part of a subcommand name.


Example:
```
. jl: using RDatasets

. jl: df = dataset("datasets", "iris")
150×5 DataFrame
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species
     │ Float64      Float64     Float64      Float64     Cat…
─────┼─────────────────────────────────────────────────────────────
   1 │         5.1         3.5          1.4         0.2  setosa
   2 │         4.9         3.0          1.4         0.2  setosa
   3 │         4.7         3.2          1.3         0.2  setosa
   4 │         4.6         3.1          1.5         0.2  setosa
   5 │         5.0         3.6          1.4         0.2  setosa
   6 │         5.4         3.9          1.7         0.4  setosa
   7 │         4.6         3.4          1.4         0.3  setosa
   8 │         5.0         3.4          1.5         0.2  setosa
  ⋮  │      ⋮           ⋮            ⋮           ⋮           ⋮
 144 │         6.8         3.2          5.9         2.3  virginica
 145 │         6.7         3.3          5.7         2.5  virginica
 146 │         6.7         3.0          5.2         2.3  virginica
 147 │         6.3         2.5          5.0         1.9  virginica
 148 │         6.5         3.0          5.2         2.0  virginica
 149 │         6.2         3.4          5.4         2.3  virginica
 150 │         5.9         3.0          5.1         1.8  virginica
                                                   135 rows omitted

. jl use df, clear
Number of observations (_N) was 0, now 150.

. list in 1/10

     +-----------------------------------------------------+
     | SepalL~h   SepalW~h   PetalL~h   PetalW~h   Species |
     |-----------------------------------------------------|
  1. |      5.1        3.5        1.4         .2    setosa |
  2. |      4.9          3        1.4         .2    setosa |
  3. |      4.7        3.2        1.3         .2    setosa |
  4. |      4.6        3.1        1.5         .2    setosa |
  5. |        5        3.6        1.4         .2    setosa |
     |-----------------------------------------------------|
  6. |      5.4        3.9        1.7         .4    setosa |
  7. |      4.6        3.4        1.4         .3    setosa |
  8. |        5        3.4        1.5         .2    setosa |
  9. |      4.4        2.9        1.4         .2    setosa |
 10. |      4.9        3.1        1.5         .1    setosa |
     +-----------------------------------------------------+
```

**Comment by droodman** [comment]
Update: I added mapping from Stata variables with value labels to categorical vectors. It's crazy inefficient. I recode the variable, replacing its values with their labels, then feed it to the CategoricalVector() constructor.

**Comment by droodman** [comment]
Now compiled on all platforms, and better debugged. Install for now with:
```
net install julia, replace from(https://raw.github.com/droodman/julia.ado/v0.10.0)
```
